model_type: flux
sample:
  logging_dir: logs
  resolution: 512
  seed: 42
  generator_seed: 0
  skip_batches: null
  dataloader_num_workers: 8
  train_json: /path/to/sample.json
  enable_xformers_memory_efficient_attention: false
  flux:
    pretrained_model_name_or_path: black-forest-labs/FLUX.1-Fill-dev
    output_dir: ../global_seed_42/batch_2/local_seed_0
    sample_batch_size: 8
    save_step: 320
    max_steps: 250
    mixed_precision: bf16
  brushnet:
    pretrained_model_name_or_path: runwayml/stable-diffusion-v1-5
    output_dir: '.../global_seed_42/local_seed_0'
    sample_batch_size: 32
    save_step: 10000
    max_steps: 500
    mixed_precision: fp16
train:
  revision: null
  variant: null
  num_train_epochs: 1
  resume_from_checkpoint: null
  max_train_steps: 1
  gradient_accumulation_steps: 1
  scale_lr: false
  lr_scheduler: constant
  lr_warmup_steps: 500
  lr_num_cycles: 1
  lr_power: 1.0
  optimizer: AdamW
  use_8bit_adam: false
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 0.01
  adam_epsilon: 1.0e-08
  max_grad_norm: 1.0
  push_to_hub: false
  hub_token: null
  hub_model_id: null
  logging_dir: logs
  allow_tf32: false
  enable_xformers_memory_efficient_attention: false
  set_grads_to_none: false
  dataset_name: null
  dataset_config_name: null
  image_column: image
  conditioning_image_column: conditioning_image
  caption_column: text
  max_train_samples: null
  proportion_empty_prompts: 0
  validation_prompt: null
  validation_image: null
  validation_mask: null
  num_validation_images: 1
  wandb_id: null
  random_mask: false
  weighting_scheme: none
  logit_mean: 0.0
  logit_std: 1.0
  mode_scale: 1.29
  height: 64
  width: 64
  max_sequence_length: 16
  seed: 42
  train_data_dir: ~/.cache/huggingface/hub/datasets--random123123--BrushData/snapshots/333cdc6dc928b6efdbe25c0b3943d1c67a85fc8f
  train_json_dir: smoke_data/flux_train/annotations/results.json
  resolution: 64
  validation_steps: 999999
  checkpointing_steps: 999999
  train_steps: 1
  dataloader_num_workers: 0
  dpo_loss_weight: 1.0
  mse_loss_weight: 0.0
  mixed_precision: bf16
  report_to: null
  guidance_scale: 1
  train_base_model: true
  dpo_new: false
  dpo_mask: true
  do_test: true
  note: null
  metrics:
    enable: false
    score_file: /path/to/results_with_ensemble.json
    metric: ensemble
    scaling: 16
  lora:
    enable: false
    lora_layers: null
    rank: 64
    alpha: 128
  flux:
    pretrained_model_name_or_path: black-forest-labs/FLUX.1-Fill-dev
    gradient_checkpointing: false
    checkpoints_total_limit: 1
    learning_rate: 1.0e-05
    train_batch_size: 1
    beta_dpo: 2000
    tracker_project_name: flux
    output_dir: smoke_data/flux_train/output
  brushnet:
    pretrained_model_name_or_path: runwayml/stable-diffusion-v1-5
    brushnet_model_name_or_path: path/to/brushnet/segmentation_mask_brushnet_ckpt
    tokenizer_name: null
    cache_dir: null
    gradient_checkpointing: false
    checkpoints_total_limit: null
    learning_rate: 1.0e-06
    train_batch_size: 8
    beta_dpo: 8000
    tracker_project_name: brushnet
    output_dir: runs/debug/brushnet
  output_dir: smoke_data/flux_train/output
  train_batch_size: 1
  pretrained_model_name_or_path: black-forest-labs/FLUX.1-Fill-dev
  gradient_checkpointing: false
